### PR TITLE
Call safe pool release

### PR DESCRIPTION
**Pull request by smolskyaleksey**
try to prevent crash on pj_pool_safe_release

### CODE REVIEW

**Comment by smolskyaleksey** [comment]
Can we post issue to pjsip about it?

**Comment by bobvoorneveld** [comment]
What do  want to post to pjsip?

**Comment by smolskyaleksey** [comment]
Сrash on pj_pool_release with EXC_BAD_ACCESS KERN_PROTECTION_FAILURE

**Comment by bobvoorneveld** [comment]
I think that's why they created that new function?

**Comment by smolskyaleksey** [comment]
I think it is not our case ((

**Comment by smolskyaleksey** [comment]
http://stackoverflow.com/a/16202073/4091184

**Pull request merged**
