### PR TITLE
add opus codec to codec list

### PR DESCRIPTION
**Pull request by smolskyaleksey**

### CODE REVIEW

**Comment by bobvoorneveld** [comment]
hi @smolskyaleksey, we're working on an improved version of Vialer-pjsip-ios version that will have an option to include Opus codec. I would like to change the code so that the opus codec will only be added to the list if PJMEDIA_HAS_OPUS_CODEC is set to true. This will make it possible to not have opus included and have a correct list also. If you need help, let me know.

**Comment by smolskyaleksey** [comment]
How long to wait update?

**Comment by bobvoorneveld** [comment]
@spindleredmer is working on it, he just told me within 2 weeks

**Comment by smolskyaleksey** [comment]
I will wait it. Now I have working version of lib, it's enough for me right now. I will work on secure audio/video calls.

**Comment by smolskyaleksey** [comment]
Could you also add H264?  It is not take a lot of time.

**Comment by spindleredmer** [comment]
Yes, i will also add the h264 codec, I just finished adding the OpenSSL for secure calling.

**Comment by smolskyaleksey** [comment]
Greate news!

**Comment by smolskyaleksey** [comment]
Also I think we should add possibility to configure codec list and priority to it. Current implementation with dictionaries is not good and it is private API. I can't modify codec priority from my code. I don't have public API for it.

**Comment by bobvoorneveld** [comment]
We just said the same to each other. We'll make it configurable, ticket has been made.

**Comment by smolskyaleksey** [comment]
Nice! Could you provide link I want to make review .

**Comment by bobvoorneveld** [comment]
We'll make it a pull request as soon as its done. Any suggestions can you put here, ticket means we haven't done anything, it's in the planning to get things going.

**Pull request closed without merging**
