### PR TITLE
On call media event

### PR DESCRIPTION
**Pull request by smolskyaleksey**
add new callback

### CODE REVIEW

**Comment by bobvoorneveld** [comment]
Tnx!

**Comment by Saurman** [comment]
@smolskyaleksey can u provide instructions or demo app on how to enabled video calling?

**Comment by smolskyaleksey** [comment]
``` objective-c
- (void)startWithCompletion:(void (^)(NSError * error))completion {
    NSAssert(self.account, @"An account must be set to be able to start a call");
    pj_str_t sipUri = [self.numberToCall sipUriWithDomain:self.account.accountConfiguration.sipDomain];

    // Create call settings.
    pjsua_call_setting callSetting;
    pjsua_call_setting_default(&callSetting);
    callSetting.aud_cnt = 1;
    callSetting.vid_cnt = 1;
    if (!self.hasVideo) {
        callSetting.vid_cnt = 0;
    } else {
        [self changeOrientationVideo:nil];
    }
    

    pj_status_t status = pjsua_call_make_call((int)self.account.accountId, &sipUri, &callSetting, NULL, NULL, (int *)&_callId);
    VSLLogVerbose(@"Call(%@) received id:%ld", self.uuid.UUIDString, (long)self.callId);

    NSError *error;
    if (status != PJ_SUCCESS) {
        VSLLogError(@"Error creating call");
        error = [NSError VSLUnderlyingError:nil
                    localizedDescriptionKey:NSLocalizedString(@"Could not setup call", nil)
                localizedFailureReasonError:[NSString stringWithFormat:NSLocalizedString(@"PJSIP status code: %d", nil), status]
                                errorDomain:VSLCallErrorDomain
                                  errorCode:VSLCallErrorCannotCreateCall];
    }
    completion(error);
}


- (void)changeOrientationVideo:(NSNotification *)note
{
#if PJSUA_HAS_VIDEO
    if (self.hasVideo) {
        static pj_thread_desc a_thread_desc;
        static pj_thread_t *a_thread;
        static UIDeviceOrientation prev_ori = 0;
        UIDeviceOrientation dev_ori = [[UIDevice currentDevice] orientation];
        int i;
        
        if (dev_ori == prev_ori) return;
        if (prev_ori == 0 && dev_ori == UIDeviceOrientationFaceUp) {
            dev_ori = UIDeviceOrientationPortrait;
        }
        VSLLogDebug(@"Device orientation changed: %d", (prev_ori = dev_ori));
        
        if (dev_ori >= UIDeviceOrientationPortrait &&
            dev_ori <= UIDeviceOrientationLandscapeRight)
        {
            /* Here we set the orientation for all video devices.
             * This may return failure for renderer devices or for
             * capture devices which do not support orientation setting,
             * we can simply ignore them.
             */
            for (i = pjsua_vid_dev_count()-1; i >= 0; i--) {
                pjsua_vid_dev_set_setting(i, PJMEDIA_VID_DEV_CAP_ORIENTATION,
                                          &pj_ori[dev_ori-1], PJ_TRUE);
            }
        }
    }
#endif
}

```

**Comment by Saurman** [comment]
@smolskyaleksey how do i configure video preview and camera views? Looks like some notifications are involved as well

**Comment by smolskyaleksey** [comment]
``` objective-c

- (void)changeOrientationVideo:(NSNotification *)note
{
#if PJSUA_HAS_VIDEO
    if (self.hasVideo) {
        static pj_thread_desc a_thread_desc;
        static pj_thread_t *a_thread;
        static UIDeviceOrientation prev_ori = 0;
        UIDeviceOrientation dev_ori = [[UIDevice currentDevice] orientation];
        int i;
        
        if (dev_ori == prev_ori) return;
        if (prev_ori == 0 && dev_ori == UIDeviceOrientationFaceUp) {
            dev_ori = UIDeviceOrientationPortrait;
        }
        VSLLogDebug(@"Device orientation changed: %d", (prev_ori = dev_ori));
        
        if (dev_ori >= UIDeviceOrientationPortrait &&
            dev_ori <= UIDeviceOrientationLandscapeRight)
        {
            /* Here we set the orientation for all video devices.
             * This may return failure for renderer devices or for
             * capture devices which do not support orientation setting,
             * we can simply ignore them.
             */
            for (i = pjsua_vid_dev_count()-1; i >= 0; i--) {
                pjsua_vid_dev_set_setting(i, PJMEDIA_VID_DEV_CAP_ORIENTATION,
                                          &pj_ori[dev_ori-1], PJ_TRUE);
            }
        }
    }
#endif
}



- (UIView *)createPreviewViewWith:(CGRect)frame{
    pjsua_vid_win_id wid = 0;
    wid = pjsua_vid_preview_get_win(self.account.accountConfiguration.camera);
    pjmedia_coord rect;
    rect.x = frame.origin.x;
    rect.y = frame.origin.y;
    pjmedia_rect_size rect_size;
    rect_size.h = frame.size.height;
    rect_size.w = frame.size.width;
    pjsua_vid_win_set_size(wid,&rect_size);
    pjsua_vid_win_set_pos(wid,&rect);
    pjsua_vid_win_info win_info;
    pjsua_vid_win_get_info(wid, &win_info);
    UIView *view = (__bridge UIView *)win_info.hwnd.info.ios.window;
    view.frame = frame;
    win_info.is_native = PJ_TRUE;
    win_info.show = YES;
    
    return view;
}


- (UIView *)createVideoWindowWithFrame:(CGRect)frame {
    int vid_idx;
    pjsua_vid_win_id wid = 0;
    vid_idx = pjsua_call_get_vid_stream_idx(_callId);
    if (vid_idx >= 0){
        pjsua_call_info ci;
        pjsua_call_get_info(_callId, &ci);
        
        wid = ci.media[vid_idx].stream.vid.win_in;
    }
    pjmedia_coord rect;
    rect.x = frame.origin.x;
    rect.y = frame.origin.y;
    pjmedia_rect_size rect_size;
    rect_size.h = frame.size.height;
    rect_size.w = frame.size.width;
    pjsua_vid_win_set_size(wid,&rect_size);
    pjsua_vid_win_set_pos(wid,&rect);
    pjsua_vid_win_info win_info;
    pjsua_vid_win_get_info(wid, &win_info);
    win_info.is_native = PJ_FALSE;
    UIView *view = (__bridge UIView *)win_info.hwnd.info.ios.window;
    pjsua_vid_win_set_show(wid, PJ_TRUE);
    
    return view;
}

- (BOOL)startPreview {
    pj_thread_desc desc;
    pj_thread_t *thread = 0;
    if(!pj_thread_is_registered())
    {
        VSLLogDebug(@"pj_thread_is_registered");
        pj_thread_register(NULL,desc,&thread);
    }
    pjsua_vid_preview_param preview_param;
    pjsua_vid_preview_param_default(&preview_param);
    preview_param.wnd_flags = PJMEDIA_VID_DEV_WND_BORDER |
    PJMEDIA_VID_DEV_WND_RESIZABLE;
    
    
    BOOL result = pjsua_vid_preview_start(self.account.accountConfiguration.camera, &preview_param) != PJ_SUCCESS;
    return !result;
}

- (void)stopPreviewView {
    [[NSNotificationCenter defaultCenter] removeObserver:self
                                                   name:UIDeviceOrientationDidChangeNotification
                                                 object:[UIDevice currentDevice]];
    
    pj_thread_desc desc;
    pj_thread_t *thread = 0;
    if(!pj_thread_is_registered())
    {
        VSLLogDebug(@"pj_thread_is_registered");
        pj_thread_register(NULL,desc,&thread);
    }
    pjsua_vid_preview_stop(self.account.accountConfiguration.camera);//PJMEDIA_VID_DEFAULT_CAPTURE_DEV
}


- (void)setCamera:(VSLCaptureDevice)cameraID {
    int vid_idx;
    vid_idx = pjsua_call_get_vid_stream_idx(self.callId);
    if (vid_idx >= 0){
        pjsua_call_vid_strm_op_param param;
        pjsua_call_vid_strm_op_param_default(&param);
        param.med_idx = vid_idx;
        param.cap_dev = cameraID;
        
        pjsua_call_set_vid_strm(self.callId,
                                PJSUA_CALL_VID_STRM_CHANGE_CAP_DEV,
                                &param);
        
    }
    
}

- (void)swithCamera {
    int vid_idx;
    vid_idx = pjsua_call_get_vid_stream_idx(self.callId);
    if (vid_idx >= 0){
        pjmedia_vid_dev_index cap_dev = 0;
        pjsua_call_info ci;
        pjsua_call_get_info(self.callId, &ci);
        cap_dev = ci.media[vid_idx].stream.vid.cap_dev;
        
        pjsua_call_vid_strm_op_param param;
        pjsua_call_vid_strm_op_param_default(&param);
        param.med_idx = vid_idx;
        param.cap_dev = cap_dev == VSLCaptureDeviceBackCamera ? VSLCaptureDeviceFrontCamera : VSLCaptureDeviceBackCamera;
        
        pjsua_call_set_vid_strm(self.callId,
                                PJSUA_CALL_VID_STRM_CHANGE_CAP_DEV,
                                &param);
        
    }
}

```

When call get status confirmed call 

``` objective-c
- (void)_showVideoViews:(VSLCall *)call {
    if (call != nil && !self.hasVideoRenderView) {
        if (call.mediaState == VSLMediaStateActive && call.hasVideo && !self.hasVideoRenderView) {
            self.hasVideoRenderView = YES;
            [VialerSIPLib sharedInstance].callManager.audioController.output = VSLAudioControllerOutputSpeaker;
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_DEFAULT, 0), ^{
                pj_thread_desc desc;
                pj_thread_t *thread = 0;
                if(!pj_thread_is_registered())
                {
                    pj_thread_register(NULL,desc,&thread);
                }

                pj_status_t status;
                pjsua_stream_info stream_info;
                status = pjsua_call_get_stream_info((pjsua_call_id)call.callId, 1, &stream_info);
                
                double codecWidth = 0.0;
                double codecHeight = 0.0;
                
                if (status == PJ_SUCCESS) {
                    if (stream_info.type == PJMEDIA_TYPE_VIDEO) {
                        pjmedia_vid_codec_param param;
                        param = *stream_info.info.vid.codec_param;
                        codecWidth = param.enc_fmt.det.vid.size.w * 1.0;
                        codecHeight = param.enc_fmt.det.vid.size.h * 1.0;
                    }
                } else {
                    DDLogError(@"Video stream info not found");
                }
                
                [call startPreview];
                dispatch_async(dispatch_get_main_queue(), ^{
                    
                    CGFloat widht = kFCPreviewDefWidth;
                    CGFloat height = kFCPreviewDefHeight;
                    
                    CGFloat widhtRenderV = CGRectGetWidth(self.view.bounds);
                    CGFloat heightRenderV = CGRectGetHeight(self.view.bounds);
                    
                    if (codecWidth != 0 && codecHeight != 0) {
                        double horizontalRatio = widht/codecWidth;
                        double verticalRatio = height/codecHeight;
                        CGFloat ratio = MIN(horizontalRatio, verticalRatio);
                        widht = codecWidth * ratio;
                        height = codecHeight * ratio;
                    }

                    heightRenderV = (widhtRenderV * widhtRenderV)/codecWidth;

                    
                    UIView *previewWindow = [call createPreviewViewWith:CGRectMake((self.view.frame.size.width - widht - 10), 120, widht, height)];
                    [self.view addSubview:previewWindow];
                    
                    [previewWindow setTranslatesAutoresizingMaskIntoConstraints:NO];
                    [previewWindow addConstraint:[NSLayoutConstraint constraintWithItem:previewWindow attribute:NSLayoutAttributeWidth relatedBy:NSLayoutRelationEqual toItem:nil
                                                                              attribute:NSLayoutAttributeNotAnAttribute multiplier:1 constant:widht]];
                    [previewWindow addConstraint:[NSLayoutConstraint constraintWithItem:previewWindow attribute:NSLayoutAttributeHeight relatedBy:NSLayoutRelationEqual toItem:nil
                                                                              attribute:NSLayoutAttributeNotAnAttribute multiplier:1 constant:height]];
                    [self.view addConstraint:[NSLayoutConstraint constraintWithItem:previewWindow attribute:NSLayoutAttributeTop relatedBy:NSLayoutRelationEqual toItem:self.bgStatusView
                                                                          attribute:NSLayoutAttributeBottom multiplier:1 constant:20]];
                    [self.view addConstraint:[NSLayoutConstraint constraintWithItem:previewWindow attribute:NSLayoutAttributeRight relatedBy:NSLayoutRelationEqual toItem:self.view
                                                                          attribute:NSLayoutAttributeRight multiplier:1 constant:-10]];
                    [self _addRenderStremViewWithSize:CGSizeMake(widhtRenderV, heightRenderV)];
                    [call changeOrientationVideo:nil];
                });
            });
        }
    }
}

```

**Pull request merged**
